- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False    
  tasks:
    - name: Echo text
      shell: 'echo "{{ greet }}"'
      register: response
    - debug:
        var: response
